---
abstract: 'Service Level Agreements for RT'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: gpl2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-SLA
no_index:
  directory:
    - etc
    - inc
    - t
requires:
  Business::Hours: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-2.0.php
version: 0.04
