---
abstract: 'Service Level Agreements for RT'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: gpl2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-SLA
no_index:
  directory:
    - etc
    - inc
    - t
requires:
  Business::Hours: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-2.0.php
version: '1.00'
x_module_install_rtx_version: 0.34_02
x_requires_rt: 4.0.0
x_rt_too_new: 4.4.0
